
# Basic synapse configuration, this is used in order to connect with synapse server
bridge:
  # Synapse server name
  domain: openearth.space
  # Synapse server url
  url: https://openearth.space:8008
  # Optional. The URL where media hosted on the synapse is reachable
  # (this should be publicly reachable from the internet)
  mediaUrl: https://openearth.space
  # Local port on which hookshot will receive events from synapse server
  port: 9002
  # This is the address on which hookshot will receive events.
  # Should stay 0.0.0.0 while using in Kubernetes.
  bindAddress: 0.0.0.0


# (Optional) Configure this to enable GitHub support
# Ref: https://matrix-org.github.io/matrix-hookshot/latest/setup/github.html
github:
  # Authentication for the GitHub App.
  auth:
    id: <auth_id>
    privateKeyFile: /data/githubKey.pem # In our configuration all keys are in /data folder
  # Webhook settings for the GitHub app.
  webhook:
    secret: secrettoken # This secrettoken must match github webhook secret, refer to documentation
  # (Optional) Settings for allowing users to sign in via OAuth.
  oauth:
    client_id: <client-id>
    client_secret: <client-secret>
    redirect_uri:  https://openearth.space/hookshot/webhook/oauth # Must be the oauth hookshot's webhook URL 
  # (Optional) Default options for GitHub connections.
  defaultOptions:
    showIssueRoomLink: false
    hotlinkIssues:
      prefix: "#"
  # (Optional) Prefix used when creating ghost users for GitHub accounts. 
  userIdPrefix:
    _github_

  
# (Optional) Configure this to enable GitLab support
# Ref: https://matrix-org.github.io/matrix-hookshot/latest/setup/gitlab.html
gitlab:
  instances:
    gitlab.com:
      url: https://gitlab.com
  webhook:
    secret: secrettoken # This secrettoken must match gitlab's webhook secret, refer to documentation
    publicUrl: https://openearth.space/hookshot/webhook/ # Must be the URL where GitLab webhook events are received (i.e. the path to / for your webhooks listener).
  # (Optional) Prefix used when creating ghost users for GitLab accounts.
  userIdPrefix:
    _gitlab_


# (Optional) Configure this to enable Figma support
# Ref: https://matrix-org.github.io/matrix-hookshot/latest/setup/figma.html
figma:
  publicUrl: https://openearth.space/hookshot/webhook/ # Must be the URL where Figma webhook events are received (i.e. the path to / for your webhooks listener).
  instances:
    your-instance:
      teamId: <your-team-id>
      accessToken: <your-personal-access-token>>
      passcode: <your-webhook-passcode>


# (Optional) Configure this to enable Jira support. Only specify `url` if you are using a On Premise install (i.e. not atlassian.com)
# Ref: https://matrix-org.github.io/matrix-hookshot/latest/setup/jira.html
jira:
  # Webhook settings for JIRA
  webhook:
    secret: secrettoken # This secrettoken must match jira's webhook secret, refer to documentation
  # (Optional) OAuth settings for connecting users to JIRA. See documentation for more information
  oauth:
    client_id: <client_id>
    client_secret: <client_secret>
    redirect_uri: https://openearth.space/hookshot/webhook/jira/oauth # Must be the oauth hookshot's webhook URL 


# (Optional) Support for generic webhook events.
# Ref: https://matrix-org.github.io/matrix-hookshot/latest/setup/webhooks.html
generic:
  enabled: false 
  enableHttpGet: false
  urlPrefix: https://openearth.space/hookshot/webhook/ # Must be the URL where hookshot webhook events are received (i.e. the path to / for your webhooks listener).
  userIdPrefix: _webhooks_ #  Prefix used when creating ghost users for webhooks accounts.
  allowJsTransformationFunctions: false
  waitForComplete: false


# (Optional) Configure this to enable RSS/Atom feed support
# Ref: https://matrix-org.github.io/matrix-hookshot/latest/setup/feeds.html
feeds:
  enabled: false
  pollConcurrency: 4
  pollIntervalSeconds: 600
  pollTimeoutSeconds: 30


# (Optional) Provisioning API for integration managers
# Ref: https://matrix-org.github.io/matrix-hookshot/latest/advanced/provisioning.html
provisioning:
  secret: "!secretToken" 

# A passkey used to encrypt tokens stored inside the bridge. ( autogenerated while executing make create-hookshot-config-file )
passFile:
  /data/passkey.pem 


# Define profile information for the bot user
bot:
  displayname: Hookshot Bot 
  avatar: mxc://half-shot.uk/2876e89ccade4cb615e210c458e2a7a6883fe17d # avatar must use mxc protocol


# (Optional) Define additional bot users for specific services
# Ref: https://matrix-org.github.io/matrix-hookshot/latest/advanced/service_bots.html
serviceBots: []
  # - localpart: feeds
  #   displayname: Feeds
  #   avatar: mxc://half-shot.uk/2876e89ccade4cb615e210c458e2a7a6883fe17d
  #   prefix: "!feeds"
  #   service: feeds

# (Optional) Prometheus metrics support
# Ref: https://matrix-org.github.io/matrix-hookshot/latest/metrics.html
metrics:
  enabled: false

# (Optional) Message queue / cache configuration options for large scale deployments.
# For encryption to work, must be set to monolithic mode and have a host & port specified.
# Ref: 
queue:
  monolithic: true
  port: 6379
  host: localhost


# (Optional) Logging settings. You can have a severity debug,info,warn,error
logging:
  level: info
  colorize: true
  json: false
  timestampFormat: HH:mm:ss:SSS


# (Optional)[EXPERIMENTAL] support for complimentary widgets
# Red: https://matrix-org.github.io/matrix-hookshot/latest/advanced/widgets.html
widgets:
  addToAdminRooms: false
  disallowedIpRanges:
    - 127.0.0.0/8
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 100.64.0.0/10
    - 192.0.0.0/24
    - 169.254.0.0/16
    - 192.88.99.0/24
    - 198.18.0.0/15
    - 192.0.2.0/24
    - 198.51.100.0/24
    - 203.0.113.0/24
    - 224.0.0.0/4
    - ::1/128
    - fe80::/10
    - fc00::/7
    - 2001:db8::/32
    - ff00::/8
    - fec0::/10
  roomSetupWidget:
    addOnInvite: false
  publicUrl: https://example.com/widgetapi/v1/static/
  branding:
    widgetTitle: Hookshot Configuration


# (Optional) Configure Sentry error reporting
# Ref: https://matrix-org.github.io/matrix-hookshot/latest/sentry.html
sentry:
  dsn:  <sentary-url>
  environment: production

# (Optional) Permissions for using the bridge. See docs/setup.md#permissions for help
# Ref: https://matrix-org.github.io/matrix-hookshot/latest/setup.html#permissions
permissions:
  - actor: openearth.space # All users with this doamin will have admin access to hookshot
    services:
      - service: "*"
        level: admin

# (Optional) HTTP Listener configuration.
# Bind resource endpoints to ports and addresses.
# 'port' must be specified. Each listener must listen on a unique port.
# 'bindAddress' will default to '127.0.0.1' if not specified, which may not be suited to Docker environments.
# 'resources' may be any of webhooks, widgets, metrics, provisioning
listeners:
  - port: 9000
    bindAddress: 0.0.0.0
    resources:
      - webhooks
  - port: 9001
    bindAddress: 0.0.0.0
    resources:
      - metrics
      - provisioning
  - port: 9005
    bindAddress: 0.0.0.0
    resources:
      - widgets
      