# Hookshot registration id. This can be anything, but must be unique within your synapse server
id: matrix-hookshot
# AppSecret token, this can be a random string
as_token: aaaaaaaaaa
# HomeserverSecret token, this can be a random string
hs_token: aaaaaaaaaa

namespaces:
  rooms: []
  # Below we prevent users from registering using the following regexes,
  # hookshot will also use them while creating bot accounts.
  # You can delete the ones you won't use.
  # All _something_ should match userIdPrefixes in config file.
  # Change "openearth.space" to your synapse's server name.
  users:
    - regex: "@_github_.*:openearth.space"
      exclusive: true
    - regex: "@_gitlab_.*:openearth.space"
      exclusive: true
    - regex: "@_jira_.*:openearth.space"
      exclusive: true
    - regex: "@_webhooks_.*:openearth.space"
      exclusive: true
      # Matches the localpart of all serviceBots in hookshot's configuration file
    - regex: "@feeds:openearth.space"
      exclusive: true
  aliases:
    - regex: "#github_.+:openearth.space"
      exclusive: true

sender_localpart: hookshot

# This should match hookshot's appservice URL 
url: "https://openearth.space:9002"
rate_limited: false

# [EXPERIMENTAL] If enabling encryption
de.sorunome.msc2409.push_ephemeral: true
push_ephemeral: true
org.matrix.msc3202: true
