{{- if .Values.wellknown.enabled }}
{{- $wkName := include "matrix-synapse.externalname" (dict "global" . "external" "wellknown-lighttpd") -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $wkName }}
  labels:
    {{- include "matrix-synapse.labels" . | nindent 4 }}
    component: well-known
data:
  lighttpd.conf: |
    server.port = 8080
    {{ if .Values.wellknown.useIpv6}}
    server.use-ipv6 = "enable"
    {{ end }}
    server.modules = (
      "mod_rewrite",
      "mod_status",
      "mod_accesslog",
      "mod_extforward",
      "mod_setenv"
    )
    include "conf.d/00-mime-types.conf"
    server.username      = "lighttpd"
    server.groupname     = "lighttpd"
    server.document-root = {{ .Values.wellknown.htdocsPath | quote }}
    server.pid-file      = "/run/lighttpd.pid"
    url.rewrite-once     = (
{{- $keys := concat (list "client" "server") (keys .Values.wellknown.extraData) }}
{{- range $key := initial $keys }}
      "^/\.well-known/matrix/{{ $key }}" => "/{{ $key }}.json",
{{- end }}
      "^/\.well-known/matrix/{{ last $keys }}" => "/{{ last $keys }}.json"
    )
    status.status-url    = "/server-status"
    extforward.forwarder = ( "all" => "trust")
    setenv.add-response-header = (
      "access-control-allow-headers" => "Origin, X-Requested-With, Content-Type, Accept, Authorization",
      "access-control-allow-methods" => "GET, POST, PUT, DELETE, OPTIONS",
      "access-control-allow-origin" => "*"
    )
    setenv.set-response-header = (
      "content-type" => "application/json"
    )
  server.json: |-
{{-   if .Values.wellknown.server }}
{{ toJson .Values.wellknown.server | nindent 4 }}
{{-   else }}
{{ dict "m.server" (printf "%s:%d" (.Values.wellknown.host | default (.Values.publicServerName | default .Values.serverName)) (.Values.wellknown.port | default 443)) | toJson | indent 4 }}
{{-   end }}
  client.json: |-
{{-   if .Values.wellknown.client }}
{{ toJson .Values.wellknown.client | nindent 4 }}
{{-   else }}
{{ dict "m.homeserver" (dict "base_url" (printf "https://%s/" (.Values.publicServerName | default .Values.serverName))) | toJson | indent 4 }}
{{-   end }}
{{-   range $key, $value := .Values.wellknown.extraData }}
  {{ $key }}.json: |-
{{-     if $value | kindIs "string" -}}
    {{ $value | nindent 4 }}
{{-     else -}}
    {{ $value | toJson | nindent 4 }}
{{-     end -}}
{{-   end -}}
{{- end -}}
